=== prolog/shadow-of-the-wyrm/data/maps/world/WorldMapAreas.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="urn:savage_lands:maps:world_map:1.0.0" targetNamespace="urn:savage_lands:maps:world_map:1.0.0" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0.0.0">
	<!-- Elements -->
	<xs:element name="WorldMap" type="tns:WorldMapType"/>
	<!-- Complex Types -->
	<xs:complexType name="WorldMapType">
		<xs:sequence>
			<xs:element name="Areas" type="tns:AreasType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AreasType">
		<xs:sequence>
			<xs:element name="Area" type="tns:AreaType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AreaType">
		<xs:sequence>
			<xs:element name="Row" type="tns:RowType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Script" type="xs:string" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="RowType">
		<xs:simpleContent>
		  <xs:extension base="xs:string">
				<xs:attribute name="y" type="xs:integer"/>
				<xs:attribute name="x" type="xs:integer"/>
		  </xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== prolog/shadow-of-the-wyrm/data/maps/world/WorldMapAreas.xml
<WorldMap xmlns="urn:shadow_of_the_wyrm:maps:world_map:1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:shadow_of_the_wyrm:maps:world_map:1.0.0 ./WorldMapAreas.xsd">
	<Areas>
		<Area id="little_island">
			<Row y="92" x="94">~~~~~~</Row>
			<Row y="93" x="94">~~~~r~</Row>
			<Row y="94" x="94">~~~~~~</Row>
			<Row y="95" x="94">~KF~~~</Row>
			<Row y="96" x="94">~~vgO~</Row>
			<Row y="97" x="94">~~~~d~</Row>
			<Row y="98" x="94">FCf~~~</Row>
			<Script>areas/little_island.lua</Script>
		</Area>
		<Area id="aeschburh">
			<Row y="82" x="82">~~~~~~</Row>
			<Row y="83" x="82">~F~~~~</Row>
			<Row y="84" x="82">~vff~~</Row>
			<Row y="85" x="82">~~~~~~</Row>
			<Row y="86" x="82">~~~~~~</Row>
			<Script>areas/aeschburh.lua</Script>
		</Area>
		<Area id="infinite_dungeon">
			<Row y="87" x="97">~~~</Row>
			<Row y="88" x="97">~F~</Row>
			<Row y="89" x="97">FdF</Row>
			<Row y="90" x="97">~F~</Row>
			<Row y="91" x="97">~~~</Row>
			<Script>areas/infinite_dungeon.lua</Script>
		</Area>
		<Area id="sky_shrine">
			<Row y="1" x="87">~~~~</Row>
			<Row y="2" x="87">~~f~</Row>
			<Row y="3" x="87">~~h~</Row>
			<Row y="4" x="87">~ff~</Row>
			<Row y="5" x="87">~~~~</Row>
			<Script>areas/sky_shrine.lua</Script>
		</Area>
		<Area id="nether_shrine">
			<Row y="95" x="0">~~~~~</Row>
			<Row y="96" x="0">~mmm~</Row>
			<Row y="97" x="0">~mhm~</Row>
			<Row y="98" x="0">~mmm~</Row>
			<Row y="99" x="0">~~~~~</Row>
			<Script>areas/nether_shrine.lua</Script>
		</Area>
		<Area id="infinite_sewer">
			<Row y="80" x="76">~~~~~</Row>
			<Row y="81" x="76">~~O~~</Row>
			<Row y="82" x="76">~ff+~</Row>
			<Row y="83" x="76">~~~~~</Row>
			<Script>areas/infinite_sewer.lua</Script>
		</Area>
		<Area id="far_reaches">
			<Row y="0" x="0">~~~~~~</Row>
			<Row y="1" x="0">~~^^^~</Row>
			<Row y="2" x="0">~^c^^~</Row>
			<Row y="3" x="0">~^^^~~</Row>
			<Row y="4" x="0">~~~~~~</Row>
			<Script>areas/far_reaches.lua</Script>
		</Area>
		<Area id="atua_elar">
			<Row y="88" x="13">~~~~~~~~</Row>
			<Row y="89" x="13">~v~~~~~~</Row>
			<Row y="90" x="13">~~~~~~~~</Row>
			<Row y="91" x="13">~~~^~^~~</Row>
			<Row y="92" x="13">~~~^v^~~</Row>
			<Row y="93" x="13">~~~^^^~~</Row>
			<Row y="94" x="13">~~~~~~~~</Row>
			<Script>areas/atua_elar.lua</Script>
		</Area>
		<Area id="whalings_end">
			<Row y="96" x="78">~~~~~~~</Row>
			<Row y="97" x="78">~~~r~~~</Row>
			<Script>areas/whalings_end.lua</Script>
		</Area>
		<!-- Dwarf Lands contains the world-shrine as well -->
		<Area id="dwarf_lands">
			<Row y="4" x="7" >~~~~~~~~~~~~~~~</Row>
			<Row y="5" x="7" >~~^^~~~~~~~^~~~</Row>
			<Row y="6" x="7" >~^v^~~~~~~^f^~~</Row>
			<Row y="7" x="7" >~^^^~~~~~~~~~~~</Row>
			<Row y="8" x="7" >~~~~~~~~~^^^~~~</Row>
			<Row y="9" x="7" >~~FhF~~~~~~^v^~</Row>
			<Row y="10" x="7">~~~~~~~~~~~^^^~</Row>
			<Row y="11" x="7">~~~~~~~~~~~~~~~</Row>
			<Script>areas/dwarf_lands.lua</Script>
		</Area>
		<Area id="last_rock">
			<Row y="85" x="98">~~</Row>
			<Row y="86" x="98">~r</Row>
			<Row y="87" x="98">~~</Row>
			<Script>areas/last_rock.lua</Script>
		</Area>
		<Area id="far_shore">
			<Row y="89" x="0">~~~</Row>
			<Row y="90" x="0">F~~</Row>
			<Row y="91" x="0">~~~</Row>		
			<Script>areas/far_shore.lua</Script>
		</Area>
		<Area id="forest_of_yew">
			<Row y="60" x="79">~~~~~</Row>
			<Row y="61" x="79">~c~F~</Row>
			<Row y="62" x="79">~FFF~</Row>
			<Row y="63" x="79">~~F~~</Row>
			<Row y="64" x="79">~~~~~</Row>
			<Script>areas/forest_of_yew.lua</Script>
		</Area>
		<Area id="gnordvar">
			<Row y="47" x="92">~~~~</Row>
			<Row y="48" x="92">~~^~</Row>
			<Row y="49" x="92">~v^~</Row>
			<Row y="50" x="92">~^M~</Row>
			<Row y="51" x="92">~^~~</Row>
			<Row y="52" x="92">~~~~</Row>
			<Script>areas/gnordvar.lua</Script>
		</Area>
		<Area id="fae_caravan">
			<Row y="5" x="51">~~~~~</Row>
			<Row y="6" x="51">~~O~~</Row>
			<Row y="7" x="51">~OOO~</Row>
			<Row y="8" x="51">~~O~~</Row>
			<Row y="9" x="51">~~~~~</Row>
			<Script>areas/fae_caravan.lua</Script>
		</Area>
		<Area id="snake_lands">
			<Row y="2" x="93">~~~~~</Row>
			<Row y="3" x="93">~mm~~</Row>
			<Row y="4" x="93">~mmm~</Row>
			<Row y="5" x="93">~~K~~</Row>
			<Row y="6" x="93">~~~~~</Row>
			<Script>areas/snake_lands.lua</Script>
		</Area>
		<Area id="eka">
			<Row y="4" x="52">~~~</Row>
			<Script>areas/eka.lua</Script>
		</Area>
		<Area id="central_lands">
			<Row y="39" x="45">~~~~~~~~~~</Row>
			<Row y="40" x="45">~~~r~~~~~~</Row>
			<Row y="41" x="45">~~~~~~~~~~</Row>
			<Row y="42" x="45">~~~~~~~~~~</Row>
			<Row y="43" x="45">~m~~~FFd~~</Row>
			<Row y="44" x="45">~M~Off~~~~</Row>
			<Row y="45" x="45">~fffffff~~</Row>
			<Row y="46" x="45">~~ffff~fr~</Row>
			<Row y="47" x="45">~mmFff~~K~</Row>
			<Row y="48" x="45">~~mFFFF~~~</Row>
			<Row y="49" x="45">~~~~~~~~~~</Row>
			<Script>areas/central_lands.lua</Script>
		</Area>
	</Areas>
</WorldMap>
